[versions]
agp = "8.11.2"
jsoupVersion = "1.21.2"
kotlin = "2.0.21"
androidxCoreKtx = "1.13.1"
ktorClientAndroid = "2.3.5"
ktorClientContentNegotiation = "2.3.5"
ktorClientCore = "2.3.5"
ktorSerializationKotlinxJson = "2.3.5"
lifecycleRuntimeKtx = "2.8.4"
activityCompose = "1.9.0"
androidxComposeBom = "2024.08.00"
lifecycleViewmodelCompose = "2.8.4"
retrofit = "2.11.0"
converterGson = "2.11.0"
loggingInterceptor = "4.12.0"
kotlinxCoroutinesAndroid = "1.8.1"

[libraries]
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidxCoreKtx" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "androidxComposeBom" }
androidx-compose-ui = { module = "androidx.compose.ui:ui" }
androidx-compose-ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycleViewmodelCompose" }

ktor-client-android = { module = "io.ktor:ktor-client-android", version.ref = "ktorClientAndroid" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktorClientContentNegotiation" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktorClientCore" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktorSerializationKotlinxJson" }
location = { module = "com.google.android.gms:play-services-location", version = "21.3.0" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "converterGson" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "loggingInterceptor" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutinesAndroid" }
coil = { group = "io.coil-kt", name = "coil-compose", version = "2.7.0" }
jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoupVersion" }
datastore = { group = "androidx.datastore", name = "datastore-preferences", version = "1.1.4" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }